version: '3'

services:
  lists:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "80:8080"
    environment:
      - MONGODB_URI=mongodb://db:27017
  db:
    image: mongo
    restart: unless-stopped
